<Project>
    <PropertyGroup>
        <Authors>Jan Karger, Steven Kirk, mitchell.jon and Contributors</Authors>
        <PackageId>gong-avalonia-dragdrop</PackageId>
        <PackageProjectUrl>https://github.com/LIJIAOLONG96/gong-avalonia-dragdrop</PackageProjectUrl>
        <PackageTags>Avalonia;UI;XAML;DragDrop;Toolkit;Library;.NET</PackageTags>
        <PackageReleaseNotes>https://github.com/LIJIAOLONG96/gong-avalonia-dragdrop/releases</PackageReleaseNotes>
        <RepositoryUrl>https://github.com/LIJIAOLONG96/gong-avalonia-dragdrop.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GenerateLibraryLayout>true</GenerateLibraryLayout>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>$(MSBuildProjectDirectory)\..\gong.public.snk</AssemblyOriginatorKeyFile>
        <DelaySign>false</DelaySign>
        <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>
    </PropertyGroup>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))" />
</Project>